# Generated by Django 4.2.9 on 2024-01-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth',
            name='user',
        ),
    ]
